# Project FORESIGHT

## Notebook 1 - Data Understanding & Initial Exploration

### Objective

The purpose of this notebook is to:

- Load all datasets
- Understand their structure
- Check data quality
- Prepare for EDA and forecasting

Dataset Source:
Synthetic Retail Dataset – 10 Million Transactions

In [1]:
# ============================================
# Project FORESIGHT
# Data Understanding
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
# ============================================
# Load all datasets
# ============================================

base_path = "/kaggle/input/datasets/mrayyanshehzad/synthetic-retail-dataset-10-million-transactions/retail_clean_dataset/"

customers = pd.read_csv(base_path + "customer_master.csv")
inventory = pd.read_csv(base_path + "inventory_snapshot.csv")
promotions = pd.read_csv(base_path + "promotions.csv")
sales = pd.read_csv(base_path + "sales_transactions.csv")
sku = pd.read_csv(base_path + "sku_master.csv")
stores = pd.read_csv(base_path + "store_master.csv")
flags = pd.read_csv(base_path + "sku_inventory_flags.csv")

In [3]:
datasets = {
    "Customers": customers,
    "Inventory": inventory,
    "Promotions": promotions,
    "Sales": sales,
    "SKU": sku,
    "Stores": stores,
    "Flags": flags
}

for name, df in datasets.items():
    print("=" * 60)
    print(f"{name}")
    print("=" * 60)
    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")

============================================================
Customers
============================================================
Rows: 10,000
Columns: 7
============================================================
Inventory
============================================================
Rows: 21,228
Columns: 6
============================================================
Promotions
============================================================
Rows: 100
Columns: 8
============================================================
Sales
============================================================
Rows: 9,972,038
Columns: 11
============================================================
SKU
============================================================
Rows: 5,000
Columns: 7
============================================================
Stores
============================================================
Rows: 30
Columns: 5
============================================================
Flags
============================================================
Rows: 600
Columns: 6

In [4]:
for name, df in datasets.items():
    print("="*80)
    print(f"{name.upper()} DATASET")
    print("="*80)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\n")

================================================================================
CUSTOMERS DATASET
================================================================================

Shape:
(10000, 7)

Columns:
['cust_id', 'age', 'gender', 'city', 'loyalty_segment', 'preferred_channel', 'registration_date']

First 5 Rows:

,cust_id,age,gender,city,loyalty_segment,preferred_channel,registration_date
0,CUST00001,52,Female,Sukkur,Silver,Online,2021-01-01
1,CUST00002,41,Female,Karachi,Silver,Mobile App,2021-05-14
2,CUST00003,48,Female,Bahawalpur,Bronze,In-Store,2022-10-23
3,CUST00004,45,Male,Karachi,Silver,In-Store,2015-07-15
4,CUST00005,39,Female,Faisalabad,Bronze,In-Store,2024-01-02

================================================================================
INVENTORY DATASET
================================================================================

Shape:
(21228, 6)

Columns:
['store_id', 'sku_id', 'stock_on_hand', 'reorder_point', 'safety_stock', 'last_restock_date']

First 5 Rows:

,store_id,sku_id,stock_on_hand,reorder_point,safety_stock,last_restock_date
0,ST11,SKU02558,323,72,22,2025-05-17
1,ST21,SKU01031,236,67,14,2025-06-17
2,ST26,SKU02129,433,96,34,2025-05-20
3,ST19,SKU02907,178,34,13,2025-08-03
4,ST05,SKU01023,333,97,22,2025-07-12

================================================================================
PROMOTIONS DATASET
================================================================================

Shape:
(100, 8)

Columns:
['promo_id', 'promo_name', 'start_date', 'end_date', 'discount_pct', 'promo_type', 'target_type', 'target_value']

First 5 Rows:

,promo_id,promo_name,start_date,end_date,discount_pct,promo_type,target_type,target_value
0,PROMO001,Spring Discount Days,2024-07-28,2024-08-02,15.1,BOGO,Brand,NovaFresh
1,PROMO002,Summer Savings Event,2023-03-09,2023-03-21,7.0,Bundle Offer,All,All
2,PROMO003,Payday Discount Days,2025-04-30,2025-05-26,10.2,BOGO,Brand,ZestyCo
3,PROMO004,Super Sale,2025-06-07,2025-06-17,15.9,Clearance,SKU,SKU01108
4,PROMO005,Festive Discount Days,2024-03-23,2024-04-08,46.0,Bundle Offer,All,All

================================================================================
SALES DATASET
================================================================================

Shape:
(9972038, 11)

Columns:
['date', 'receipt_id', 'store_id', 'sku_id', 'customer_id', 'quantity', 'unit_price', 'total_value', 'channel', 'discount_pct', 'promo_id']

First 5 Rows:

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
0,2025-04-02,RCPT00000001,ST16,SKU02498,CUST01410,1,2379.11,2379.11,In-Store,0.0,NaN
1,2025-04-02,RCPT00000001,ST16,SKU04596,CUST01410,3,335.55,1006.65,In-Store,0.0,NaN
2,2022-04-24,RCPT00000002,ST15,SKU00078,CUST00134,1,820.53,820.53,Online,0.0,NaN
3,2022-04-24,RCPT00000002,ST15,SKU00554,CUST00134,2,88.32,176.64,Online,0.0,NaN
4,2024-09-22,RCPT00000003,ST20,SKU03727,CUST08826,1,1660.93,1660.93,Online,0.0,NaN

================================================================================
SKU DATASET
================================================================================

Shape:
(5000, 7)

Columns:
['sku_id', 'sku_name', 'category', 'subcategory', 'unit_price', 'cost_price', 'brand']

First 5 Rows:

,sku_id,sku_name,category,subcategory,unit_price,cost_price,brand
0,SKU00001,NutriPlus Cookware Large,Home & Kitchen,Cookware,813.41,619.77,NutriPlus
1,SKU00002,CrispKing Bread Family Pack,Dairy & Bakery,Bread,70.38,49.57,CrispKing
2,SKU00003,SoftTouch Notebooks 2L,Stationery & Office,Notebooks,151.28,83.67,SoftTouch
3,SKU00004,SunriseFoods Eggs Large,Dairy & Bakery,Eggs,233.64,156.32,SunriseFoods
4,SKU00005,SunriseFoods Pest Control Pack of 6,Home Care,Pest Control,138.50,83.46,SunriseFoods

================================================================================
STORES DATASET
================================================================================

Shape:
(30, 5)

Columns:
['store_id', 'store_name', 'city', 'store_type', 'opening_date']

First 5 Rows:

,store_id,store_name,city,store_type,opening_date
0,ST01,Quetta Convenience Store #01,Quetta,Convenience Store,2017-07-08
1,ST02,Islamabad Express Store #02,Islamabad,Express Store,2019-05-08
2,ST03,Sialkot Supermarket #03,Sialkot,Supermarket,2019-03-28
3,ST04,Multan Supermarket #04,Multan,Supermarket,2017-10-08
4,ST05,Karachi Supermarket #05,Karachi,Supermarket,2020-11-03

================================================================================
FLAGS DATASET
================================================================================

Shape:
(600, 6)

Columns:
['sku_id', 'flag', 'affected_stores', 'window_start', 'window_end', 'notes']

First 5 Rows:

,sku_id,flag,affected_stores,window_start,window_end,notes
0,SKU04321,STOCKOUT_RISK,ST12;ST28;ST25;ST11;ST20;ST15;ST21;ST04;ST03,2025-11-13,2025-12-11,High-demand SKU; simulated recent stockout win...
1,SKU04596,STOCKOUT_RISK,ST30;ST11;ST16;ST17;ST24;ST22;ST13;ST07;ST20;ST27,2025-10-31,2025-11-17,High-demand SKU; simulated recent stockout win...
2,SKU03727,STOCKOUT_RISK,ST27;ST07;ST11;ST15;ST06;ST08;ST16;ST02;ST20;S...,2025-10-17,2025-10-29,High-demand SKU; simulated recent stockout win...
3,SKU04154,STOCKOUT_RISK,ST25;ST26;ST30;ST29;ST22;ST06;ST13;ST11;ST09;S...,2025-10-28,2025-11-24,High-demand SKU; simulated recent stockout win...
4,SKU00953,STOCKOUT_RISK,ST07;ST04;ST12;ST08;ST25;ST28;ST15;ST16;ST10,2025-12-15,2025-12-29,High-demand SKU; simulated recent stockout win...